<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Authors>Microsoft Research</Authors>
    <Company>Microsoft Corporation</Company>
    <Description>.NET wrapper examples for Microsoft SEAL</Description>
    <Copyright>Microsoft Corporation 2022</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>C:/hu/decision-tree-he/SEAL_Build/bin/dotnet/$(Configuration)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(ProjectDir)../src/SEALNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SEALCBinaryFiles Condition="$([MSBuild]::IsOsPlatform(Windows))" Include="C:/hu/decision-tree-he/SEAL_Build/bin/Release\sealc.dll" />
    <SEALCBinaryFiles Condition="$([MSBuild]::IsOsPlatform(Linux))" Include="C:/hu/decision-tree-he/SEAL_Build/lib/libsealc.so*" />
    <SEALCBinaryFiles Condition="$([MSBuild]::IsOsPlatform(OSX))" Include="C:/hu/decision-tree-he/SEAL_Build/lib/libsealc*.dylib" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="@(SEALCBinaryFiles)" DestinationFolder="$(TargetDir)" />
  </Target>

  <ItemGroup>
    <Compile Include="C:/hu/decision-tree-he/SEAL\dotnet\examples\**\*.cs" />
  </ItemGroup>
</Project>
